# Generated by Django 5.0.1 on 2026-04-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total area in m²', max_digits=10)),
                ('available_area', models.DecimalField(decimal_places=2, help_text='Available area in m²', max_digits=10)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, help_text='Price per m² per month (VND)', max_digits=10)),
                ('description', models.TextField()),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industrial Zone',
                'verbose_name_plural': 'Industrial Zones',
                'db_table': 'industrial_zones',
                'ordering': ['-created_at'],
            },
        ),
    ]
