# Generated by Django 5.0.1 on 2026-04-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.industrialzone')),
            ],
            options={
                'verbose_name': 'Zone Image',
                'verbose_name_plural': 'Zone Images',
                'db_table': 'zone_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('request_created', 'Sent a rental request'), ('request_approved', 'Approved your rental request'), ('request_rejected', 'Rejected your rental request'), ('contract_created', 'Created a new contract'), ('contract_signed', 'Signed the contract'), ('contract_expired', 'Contract has expired')], max_length=30)),
                ('target_id', models.IntegerField(help_text='ID of the related request/contract/zone')),
                ('content_type', models.CharField(choices=[('rental_request', 'Rental Request'), ('contract', 'Contract')], default='rental_request', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='zoneimage',
            constraint=models.UniqueConstraint(fields=('zone', 'image_url'), name='unique_zone_image_url'),
        ),
    ]
