# Generated by Django 5.0.1 on 2026-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_zoneimage_notification_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zoneimage',
            name='unique_zone_image_url',
        ),
        migrations.RemoveField(
            model_name='zoneimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='zoneimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zone_images/'),
        ),
        migrations.AddConstraint(
            model_name='zoneimage',
            constraint=models.UniqueConstraint(condition=models.Q(('image__isnull', False)), fields=('zone', 'image'), name='unique_zone_image'),
        ),
    ]
